export type SlideLayout =
  | 'cover'
  | 'chapter'
  | 'big-statement'
  | 'data-chart'
  | 'quote'
  | 'diagram'
  | 'image'
  | 'opinion'
  | 'matrix'
  | 'timeline'
  | 'framework'
  | 'checklist';

export type SourceKey =
  | 'aecode'
  | 'masterGuide'
  | 'pastedResearch'
  | 'mckinsey'
  | 'stanford'
  | 'microsoft'
  | 'metr'
  | 'anthropic'
  | 'openai'
  | 'gartner'
  | 'aecodeDeck';

export type ChartDatum = {
  label: string;
  value: number;
};

export type DeckSlide = {
  id: number;
  chapter: string;
  layout: SlideLayout;
  title: string;
  claim: string;
  proof: string;
  source: SourceKey;
  speakerNote: string;
  kicker?: string;
  accent?: 'blue' | 'violet' | 'mint' | 'navy' | 'green';
  metric?: {
    value: string;
    label: string;
    helper?: string;
  };
  chart?: {
    type: 'line' | 'bars' | 'stack' | 'steps';
    data: ChartDatum[];
    caption?: string;
  };
  quote?: {
    text: string;
    author: string;
    role?: string;
  };
  items?: string[];
  columns?: {
    title: string;
    items: string[];
  }[];
  timeline?: {
    year: string;
    label: string;
    detail: string;
  }[];
  diagram?: {
    nodes: string[];
    caption?: string;
  };
  visual?: 'orb' | 'network' | 'city' | 'factory' | 'brain' | 'agents' | 'aec' | 'risk' | 'passport';
};

export const sourceRegistry: Record<SourceKey, { label: string; url?: string }> = {
  aecode: { label: 'AECODE - criterio editorial' },
  masterGuide: { label: 'Guia maestra de IA para liderar, construir y ejecutar' },
  pastedResearch: { label: 'Investigacion base pegada por Alejandro' },
  aecodeDeck: { label: 'Decks AECODE/KAMAN enviados por Alejandro' },
  mckinsey: {
    label: 'McKinsey - The State of AI in 2025',
    url: 'https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai',
  },
  stanford: {
    label: 'Stanford HAI - AI Index Report 2025',
    url: 'https://hai.stanford.edu/ai-index/2025-ai-index-report',
  },
  microsoft: {
    label: 'Microsoft Work Trend Index 2025',
    url: 'https://www.microsoft.com/en-us/worklab/work-trend-index/2025-the-year-the-frontier-firm-is-born',
  },
  metr: {
    label: 'METR - Task-Completion Time Horizons',
    url: 'https://metr.org/time-horizons/',
  },
  anthropic: {
    label: 'Anthropic Economic Index 2025',
    url: 'https://www.anthropic.com/research/anthropic-economic-index-september-2025-report?lang=us',
  },
  openai: {
    label: 'OpenAI - Codex GA',
    url: 'https://openai.com/index/codex-now-generally-available/',
  },
  gartner: {
    label: 'Gartner - Top Strategic Technology Trends 2026',
    url: 'https://www.gartner.com/en/articles/gartner-top-10-strategic-technology-trends-for-2023?sf261253796=1',
  },
};

const defaultCharts: Record<string, ChartDatum[]> = {
  adoption: [
    { label: '2017', value: 20 },
    { label: '2018', value: 47 },
    { label: '2019', value: 58 },
    { label: '2020', value: 50 },
    { label: '2021', value: 56 },
    { label: '2022', value: 50 },
    { label: '2023', value: 55 },
    { label: '2024', value: 78 },
    { label: '2025', value: 88 },
  ],
  scaleGap: [
    { label: 'Escalada', value: 7 },
    { label: 'Escalando', value: 31 },
    { label: 'Piloto', value: 30 },
    { label: 'Experimentacion', value: 32 },
  ],
  agentUse: [
    { label: 'Escalan agentes', value: 23 },
    { label: 'Experimentan', value: 39 },
    { label: 'Sin agentes', value: 38 },
  ],
  frontierFirm: [
    { label: 'Repensar estrategia', value: 82 },
    { label: 'Agentes en 12-18m', value: 81 },
    { label: 'AI regular lideres', value: 69 },
  ],
  aecodeLoop: [
    { label: 'Diagnostico', value: 20 },
    { label: 'Ruta', value: 40 },
    { label: 'Practica', value: 62 },
    { label: 'Evidencia', value: 82 },
    { label: 'Validacion', value: 100 },
  ],
};

const note = (title: string, claim: string) => `Usa esta slide para fijar la idea: ${title}. La postura es: ${claim}`;

const s = (slide: Omit<DeckSlide, 'speakerNote'> & { speakerNote?: string }): DeckSlide => ({
  ...slide,
  speakerNote: slide.speakerNote ?? note(slide.title, slide.claim),
});

export const slides: DeckSlide[] = [
  s({
    id: 1,
    chapter: 'Tesis',
    layout: 'cover',
    title: 'IA Agentic: liderar, construir y ejecutar en la nueva era',
    kicker: 'AECODE Keynote Web Deck',
    claim: 'La IA dejo de ser una herramienta: ahora es una capa operativa para redisenar trabajo, aprendizaje y ventaja competitiva.',
    proof: 'El cambio real ocurre cuando modelos, datos, herramientas, evaluacion y gobierno trabajan como sistema.',
    source: 'masterGuide',
    accent: 'blue',
    visual: 'orb',
    metric: { value: '100', label: 'slides para explicar, convencer y movilizar' },
  }),
  s({
    id: 2,
    chapter: 'Tesis',
    layout: 'big-statement',
    title: 'La pregunta ya no es si vas a usar IA.',
    claim: 'La pregunta correcta es que parte de tu operacion vas a convertir en sistema inteligente.',
    proof: 'Usar chat ahorra minutos; redisenar workflows cambia costos, velocidad y poder de decision.',
    source: 'masterGuide',
    accent: 'violet',
  }),
  s({
    id: 3,
    chapter: 'Tesis',
    layout: 'opinion',
    title: 'Postura AECODE',
    claim: 'La ventaja no sera saber prompts: sera saber convertir conocimiento tecnico en ejecucion verificable.',
    proof: 'En AEC, una respuesta bonita no basta; se necesita evidencia, trazabilidad, criterio y mejora del entregable.',
    source: 'aecode',
    accent: 'mint',
    items: ['Menos show de herramientas', 'Mas arquitectura de trabajo', 'Mas evidencia aplicada'],
  }),
  s({
    id: 4,
    chapter: 'Tesis',
    layout: 'matrix',
    title: 'Tres niveles de madurez',
    claim: 'La mayoria se queda en productividad individual; el valor serio aparece en sistemas de produccion.',
    proof: 'La brecha se ve cuando pasas de preguntas sueltas a procesos con datos, permisos, evaluacion y metricas.',
    source: 'masterGuide',
    accent: 'blue',
    columns: [
      { title: 'Chat', items: ['Consulta', 'Respuesta', 'Ahorro local'] },
      { title: 'Copiloto', items: ['Contexto', 'Iteracion', 'Mejor output'] },
      { title: 'Sistema', items: ['Herramientas', 'Memoria', 'Gobierno'] },
    ],
  }),
  s({
    id: 5,
    chapter: 'Tesis',
    layout: 'diagram',
    title: 'La IA como middleware cognitivo',
    claim: 'El modelo no es el producto completo; es una capa entre conocimiento, software y decision.',
    proof: 'RAG, MCP, tool use y evaluacion convierten el modelo en parte de una arquitectura, no en una app aislada.',
    source: 'pastedResearch',
    accent: 'violet',
    diagram: { nodes: ['Datos', 'Modelo', 'Herramientas', 'Evaluacion', 'Decision'], caption: 'Sistema minimo de produccion con IA' },
  }),
  s({
    id: 6,
    chapter: 'Tesis',
    layout: 'quote',
    title: 'Una frase para abrir la conversacion',
    claim: 'La IA no reemplaza pensamiento; reemplaza trabajo que nunca fue disenado como pensamiento.',
    proof: 'Cuando una tarea no tiene criterio, contexto ni validacion, es candidata natural a automatizacion.',
    source: 'aecode',
    accent: 'navy',
    quote: { text: 'El futuro no pertenece a quien usa IA, sino a quien sabe dirigirla.', author: 'AECODE', role: 'Postura editorial' },
  }),
  s({
    id: 7,
    chapter: 'Tesis',
    layout: 'framework',
    title: 'La formula operativa',
    claim: 'Modelo + datos + herramientas + evaluacion + humano responsable = sistema confiable.',
    proof: 'Sin datos, alucina. Sin herramientas, no ejecuta. Sin evaluacion, no mejora. Sin humano, no responde ante riesgo.',
    source: 'masterGuide',
    accent: 'green',
    items: ['Modelo', 'Datos propios', 'Herramientas', 'Evaluacion', 'HITL'],
  }),
  s({
    id: 8,
    chapter: 'Tesis',
    layout: 'image',
    title: 'Del teclado al sistema nervioso',
    claim: 'La interfaz conversacional fue solo el inicio; lo que viene es inteligencia conectada a flujos reales.',
    proof: 'La adopcion fuerte no se vera como una ventana de chat, sino como sistemas que coordinan informacion y accion.',
    source: 'masterGuide',
    accent: 'mint',
    visual: 'network',
  }),
  s({
    id: 9,
    chapter: 'Tesis',
    layout: 'checklist',
    title: 'Como escuchar esta presentacion',
    claim: 'No busques una lista de herramientas: busca un mapa para decidir que construir.',
    proof: 'La herramienta cambia cada mes; los principios de arquitectura, datos, validacion y criterio duran mas.',
    source: 'aecode',
    accent: 'blue',
    items: ['Que automatizar', 'Que no delegar', 'Que medir', 'Que gobernar', 'Que aprender primero'],
  }),
  s({
    id: 10,
    chapter: 'Tesis',
    layout: 'chapter',
    title: 'Capitulo 1: adopcion real',
    claim: 'El mercado ya adopto IA; ahora falta convertir adopcion en desempeno.',
    proof: 'La siguiente seccion separa uso superficial de transformacion real.',
    source: 'mckinsey',
    accent: 'violet',
    metric: { value: '88%', label: 'organizaciones usan IA en al menos una funcion' },
  }),
  s({
    id: 11,
    chapter: 'Adopcion',
    layout: 'data-chart',
    title: 'Adopcion actual de la IA en el mundo',
    claim: 'La IA ya cruzo el umbral de adopcion masiva corporativa.',
    proof: 'McKinsey reporta 88% de organizaciones usando IA en al menos una funcion en 2025.',
    source: 'mckinsey',
    accent: 'blue',
    metric: { value: '88%', label: 'usa IA en al menos una funcion', helper: 'sube desde 78% el ano anterior' },
    chart: { type: 'line', data: defaultCharts.adoption, caption: 'Uso de IA en al menos una funcion del negocio' },
  }),
  s({
    id: 12,
    chapter: 'Adopcion',
    layout: 'data-chart',
    title: 'El problema no es adopcion. Es escala.',
    claim: 'Muchas empresas ya usan IA, pero pocas la han escalado como transformacion enterprise.',
    proof: 'McKinsey indica que casi dos tercios siguen en experimentacion o piloto.',
    source: 'mckinsey',
    accent: 'violet',
    metric: { value: '2/3', label: 'aun no escalan IA enterprise' },
    chart: { type: 'stack', data: defaultCharts.scaleGap, caption: 'Fases de uso de IA entre organizaciones' },
  }),
  s({
    id: 13,
    chapter: 'Adopcion',
    layout: 'big-statement',
    title: 'El mercado confundio acceso con transformacion.',
    claim: 'Tener cuentas de IA no significa tener una organizacion aumentada por IA.',
    proof: 'La diferencia aparece cuando se miden flujos redisenados, decisiones mas rapidas y valor financiero.',
    source: 'mckinsey',
    accent: 'navy',
  }),
  s({
    id: 14,
    chapter: 'Adopcion',
    layout: 'data-chart',
    title: 'Los agentes ya entraron al radar ejecutivo',
    claim: 'La conversacion se movio de chatbots a agentes capaces de planificar y ejecutar pasos.',
    proof: 'McKinsey reporta 62% de organizaciones al menos experimentando con agentes de IA.',
    source: 'mckinsey',
    accent: 'mint',
    metric: { value: '62%', label: 'experimenta o escala agentes' },
    chart: { type: 'bars', data: defaultCharts.agentUse, caption: 'Madurez reportada en agentes' },
  }),
  s({
    id: 15,
    chapter: 'Adopcion',
    layout: 'opinion',
    title: 'La fase peligrosa: pilotos eternos',
    claim: 'El piloto sin metrica es teatro tecnologico.',
    proof: 'Si no define costo, tiempo, calidad o riesgo reducido, el piloto solo produce entusiasmo temporal.',
    source: 'aecode',
    accent: 'green',
    items: ['Define metrica antes del demo', 'Asigna dueno operativo', 'Evalua contra baseline humano'],
  }),
  s({
    id: 16,
    chapter: 'Adopcion',
    layout: 'data-chart',
    title: 'La empresa frontera nace cuando reestructura trabajo',
    claim: 'Microsoft llama Frontier Firm a la organizacion que se redisenara alrededor de inteligencia bajo demanda.',
    proof: 'El Work Trend Index 2025 analiza 31,000 trabajadores en 31 paises y senala una transicion hacia equipos humano-agente.',
    source: 'microsoft',
    accent: 'blue',
    metric: { value: '31k', label: 'trabajadores encuestados' },
    chart: { type: 'bars', data: defaultCharts.frontierFirm, caption: 'Senales de la Frontier Firm' },
  }),
  s({
    id: 17,
    chapter: 'Adopcion',
    layout: 'quote',
    title: 'La nueva unidad de trabajo',
    claim: 'El rol profesional evoluciona de ejecutar tareas a dirigir sistemas de agentes.',
    proof: 'Microsoft describe al agent boss como quien construye, delega y gestiona agentes para amplificar impacto.',
    source: 'microsoft',
    accent: 'violet',
    quote: { text: 'Trabajar con agentes se parece a incorporar a un nuevo miembro del equipo.', author: 'Microsoft WorkLab', role: 'Lectura sobre agentes' },
  }),
  s({
    id: 18,
    chapter: 'Adopcion',
    layout: 'matrix',
    title: 'Adopcion individual vs adopcion institucional',
    claim: 'La IA individual acelera personas; la IA institucional cambia la organizacion.',
    proof: 'El salto ocurre cuando hay datos comunes, permisos, plantillas, trazabilidad y evaluacion compartida.',
    source: 'masterGuide',
    accent: 'mint',
    columns: [
      { title: 'Individual', items: ['Prompts propios', 'Resultados variables', 'Sin memoria comun'] },
      { title: 'Equipo', items: ['Playbooks', 'Repositorios', 'Revision cruzada'] },
      { title: 'Empresa', items: ['Gobierno', 'KPIs', 'Integraciones'] },
    ],
  }),
  s({
    id: 19,
    chapter: 'Adopcion',
    layout: 'image',
    title: 'La brecha sera geografica, profesional y organizacional',
    claim: 'La adopcion desigual puede ampliar la distancia entre quienes aprenden a dirigir IA y quienes solo consumen resultados.',
    proof: 'Anthropic observa adopcion desigual por geografia y tipo de uso; no todos capturan el beneficio al mismo ritmo.',
    source: 'anthropic',
    accent: 'green',
    visual: 'city',
  }),
  s({
    id: 20,
    chapter: 'Adopcion',
    layout: 'chapter',
    title: 'Capitulo 2: como funciona realmente',
    claim: 'Para liderar IA no necesitas magia; necesitas entender el mecanismo suficiente para tomar buenas decisiones.',
    proof: 'Tokens, embeddings, atencion e inferencia explican por que la IA es potente y por que falla.',
    source: 'masterGuide',
    accent: 'blue',
  }),
  s({
    id: 21,
    chapter: 'Funcionamiento',
    layout: 'framework',
    title: 'El mapa mental correcto',
    claim: 'La IA moderna se entiende mejor por capas que por marcas.',
    proof: 'Simbolica, machine learning, deep learning, transformers y agentes son saltos de mecanismo, no solo nombres comerciales.',
    source: 'masterGuide',
    accent: 'violet',
    items: ['Reglas', 'Patrones', 'Representaciones', 'Generacion', 'Accion'],
  }),
  s({
    id: 22,
    chapter: 'Funcionamiento',
    layout: 'diagram',
    title: 'Tokens: la materia prima',
    claim: 'El modelo no lee palabras como un humano; procesa unidades estadisticas llamadas tokens.',
    proof: 'La tokenizacion convierte texto en piezas manipulables por una red neuronal.',
    source: 'pastedResearch',
    accent: 'blue',
    diagram: { nodes: ['Texto', 'Tokens', 'Vectores', 'Prediccion'], caption: 'De lenguaje humano a calculo probabilistico' },
  }),
  s({
    id: 23,
    chapter: 'Funcionamiento',
    layout: 'image',
    title: 'Embeddings: significado como geometria',
    claim: 'Buscar por significado exige convertir ideas en coordenadas.',
    proof: 'Los embeddings ubican conceptos similares cerca en un espacio vectorial multidimensional.',
    source: 'masterGuide',
    accent: 'mint',
    visual: 'brain',
  }),
  s({
    id: 24,
    chapter: 'Funcionamiento',
    layout: 'big-statement',
    title: 'Un modelo no sabe. Calcula probabilidades.',
    claim: 'La utilidad aparece cuando esa probabilidad se conecta con contexto y validacion.',
    proof: 'Por eso una respuesta puede sonar brillante y aun asi estar equivocada.',
    source: 'masterGuide',
    accent: 'navy',
  }),
  s({
    id: 25,
    chapter: 'Funcionamiento',
    layout: 'diagram',
    title: 'Attention: mirar todo el contexto a la vez',
    claim: 'El Transformer reemplazo lectura secuencial por relaciones paralelas entre tokens.',
    proof: 'La autoatencion permite ponderar que partes del contexto importan para la siguiente prediccion.',
    source: 'pastedResearch',
    accent: 'violet',
    diagram: { nodes: ['Query', 'Key', 'Value', 'Peso', 'Contexto'], caption: 'La atencion decide que informacion pesa mas' },
  }),
  s({
    id: 26,
    chapter: 'Funcionamiento',
    layout: 'timeline',
    title: 'De Turing a Transformers',
    claim: 'La IA no aparecio de golpe: se acelero cuando datos, computo y arquitectura coincidieron.',
    proof: 'El salto contemporaneo se consolida con la arquitectura Transformer de 2017.',
    source: 'pastedResearch',
    accent: 'blue',
    timeline: [
      { year: '1950', label: 'Turing', detail: 'La pregunta por maquinas inteligentes.' },
      { year: '1956', label: 'Dartmouth', detail: 'Nace formalmente el termino IA.' },
      { year: '2017', label: 'Transformer', detail: 'Autoatencion y entrenamiento paralelo.' },
      { year: '2022+', label: 'GenAI', detail: 'IA generativa se vuelve masiva.' },
    ],
  }),
  s({
    id: 27,
    chapter: 'Funcionamiento',
    layout: 'matrix',
    title: 'Entrenamiento vs inferencia',
    claim: 'Confundir entrenamiento con uso diario lleva a malas decisiones tecnicas.',
    proof: 'Entrenar ajusta pesos; inferir usa pesos ya aprendidos para producir una salida.',
    source: 'masterGuide',
    accent: 'green',
    columns: [
      { title: 'Entrenar', items: ['Datos masivos', 'Costo alto', 'Ajuste de pesos'] },
      { title: 'Inferir', items: ['Prompt activo', 'Costo variable', 'Respuesta probabilistica'] },
      { title: 'Evaluar', items: ['Tests', 'Rubricas', 'Comparacion contra verdad'] },
    ],
  }),
  s({
    id: 28,
    chapter: 'Funcionamiento',
    layout: 'quote',
    title: 'Analogía de cocina',
    claim: 'Tokens son ingredientes; embeddings son despensa; attention es el cocinero mirando que importa.',
    proof: 'La analogia ayuda a explicar sin perder rigor: el modelo combina patrones aprendidos, no conciencia.',
    source: 'masterGuide',
    accent: 'mint',
    quote: { text: 'No necesitas idolatrar el modelo; necesitas entender su cocina.', author: 'AECODE', role: 'Explicacion tecnica' },
  }),
  s({
    id: 29,
    chapter: 'Funcionamiento',
    layout: 'checklist',
    title: 'Por que falla una IA',
    claim: 'Los errores son previsibles cuando conoces el mecanismo.',
    proof: 'Falta de contexto, datos ambiguos, objetivo mal definido o ausencia de verificacion producen salidas fragiles.',
    source: 'masterGuide',
    accent: 'violet',
    items: ['Contexto incompleto', 'Fuente no verificada', 'Instruccion ambigua', 'No hay tests', 'No hay responsable'],
  }),
  s({
    id: 30,
    chapter: 'Funcionamiento',
    layout: 'chapter',
    title: 'Capitulo 3: de chat a sistemas',
    claim: 'El salto profesional es pasar de conversar con IA a construir arquitectura con IA.',
    proof: 'RAG, fine-tuning, memoria, herramientas y evaluacion son el puente hacia produccion.',
    source: 'masterGuide',
    accent: 'blue',
  }),
  s({
    id: 31,
    chapter: 'Sistemas',
    layout: 'big-statement',
    title: 'ChatGPT no es tu estrategia de IA.',
    claim: 'Es una interfaz. La estrategia vive en tus datos, procesos, roles y controles.',
    proof: 'Sin arquitectura, cada usuario inventa su propio sistema y la organizacion pierde aprendizaje acumulado.',
    source: 'aecode',
    accent: 'navy',
  }),
  s({
    id: 32,
    chapter: 'Sistemas',
    layout: 'diagram',
    title: 'RAG: IA a libro abierto',
    claim: 'RAG reduce alucinaciones al recuperar informacion real antes de responder.',
    proof: 'El modelo consulta documentos indexados, selecciona contexto y lo usa en la respuesta.',
    source: 'masterGuide',
    accent: 'mint',
    diagram: { nodes: ['Pregunta', 'Busqueda vectorial', 'Contexto', 'Modelo', 'Respuesta citada'], caption: 'Retrieval-Augmented Generation' },
  }),
  s({
    id: 33,
    chapter: 'Sistemas',
    layout: 'matrix',
    title: 'RAG vs fine-tuning',
    claim: 'RAG actualiza conocimiento; fine-tuning moldea comportamiento.',
    proof: 'Usarlos como rivales simplifica demasiado: muchas arquitecturas maduras combinan ambos.',
    source: 'masterGuide',
    accent: 'blue',
    columns: [
      { title: 'RAG', items: ['Datos cambiantes', 'Citas', 'Menos costo inicial'] },
      { title: 'Fine-tuning', items: ['Estilo estable', 'Formato', 'Especializacion'] },
      { title: 'Hibrido', items: ['Contexto + conducta', 'Mejor QA', 'Escala controlada'] },
    ],
  }),
  s({
    id: 34,
    chapter: 'Sistemas',
    layout: 'image',
    title: 'La base vectorial es memoria semantica',
    claim: 'No basta guardar archivos: hay que volverlos recuperables por significado.',
    proof: 'Embeddings y similitud semantica permiten encontrar documentos relacionados aunque no compartan palabras exactas.',
    source: 'pastedResearch',
    accent: 'green',
    visual: 'network',
  }),
  s({
    id: 35,
    chapter: 'Sistemas',
    layout: 'framework',
    title: 'Arquitectura minima de un copiloto serio',
    claim: 'Un copiloto de produccion necesita mas que prompt engineering.',
    proof: 'Requiere identidad, permisos, contexto, herramientas, logging, evaluacion y fallback.',
    source: 'masterGuide',
    accent: 'violet',
    items: ['Auth', 'RAG', 'Tool use', 'Logs', 'Eval set', 'Fallback'],
  }),
  s({
    id: 36,
    chapter: 'Sistemas',
    layout: 'opinion',
    title: 'La interfaz debe esconder complejidad, no eliminarla',
    claim: 'El usuario merece una experiencia simple; el sistema necesita arquitectura rigurosa.',
    proof: 'La simplicidad sin infraestructura termina en respuestas lindas pero no auditables.',
    source: 'aecode',
    accent: 'mint',
    items: ['UI simple', 'Backend trazable', 'Evaluacion continua'],
  }),
  s({
    id: 37,
    chapter: 'Sistemas',
    layout: 'data-chart',
    title: 'El valor nace en el workflow',
    claim: 'La IA high performer redisenha flujos, no solo agrega asistentes.',
    proof: 'McKinsey encuentra que los high performers son mucho mas propensos a redisenar workflows e innovar con IA.',
    source: 'mckinsey',
    accent: 'blue',
    metric: { value: '3x', label: 'mas probabilidad de escalar agentes en high performers', helper: 'segun McKinsey' },
    chart: { type: 'bars', data: [{ label: 'Pares', value: 35 }, { label: 'High performers', value: 100 }], caption: 'Indice ilustrativo basado en brecha relativa reportada' },
  }),
  s({
    id: 38,
    chapter: 'Sistemas',
    layout: 'checklist',
    title: 'Preguntas antes de construir un sistema IA',
    claim: 'La arquitectura se decide desde el caso de uso, no desde la moda.',
    proof: 'Una buena pregunta tecnica evita seis meses de deuda y demos inconexos.',
    source: 'aecode',
    accent: 'green',
    items: ['Que decide?', 'Con que datos?', 'Que herramienta usa?', 'Como falla?', 'Como se valida?'],
  }),
  s({
    id: 39,
    chapter: 'Sistemas',
    layout: 'quote',
    title: 'La memoria privada es el activo',
    claim: 'Tu ventaja no sera tener acceso al mismo modelo que todos, sino mejor contexto propio.',
    proof: 'La diferenciacion aparece cuando tus documentos, taxonomias y evidencia alimentan el sistema.',
    source: 'masterGuide',
    accent: 'violet',
    quote: { text: 'El modelo se compra. El contexto se construye.', author: 'AECODE', role: 'Criterio de arquitectura' },
  }),
  s({
    id: 40,
    chapter: 'Sistemas',
    layout: 'chapter',
    title: 'Capitulo 4: agentes',
    claim: 'Un agente no solo responde: percibe contexto, decide pasos, usa herramientas y verifica resultados.',
    proof: 'El salto agentic es pasar de output a accion controlada.',
    source: 'masterGuide',
    accent: 'mint',
    visual: 'agents',
  }),
  s({
    id: 41,
    chapter: 'Agentes',
    layout: 'diagram',
    title: 'Que es un agente de IA',
    claim: 'Un agente es un sistema que transforma una meta en acciones sobre herramientas.',
    proof: 'Planifica, llama funciones, observa resultados y ajusta su siguiente paso.',
    source: 'masterGuide',
    accent: 'blue',
    diagram: { nodes: ['Meta', 'Plan', 'Tool use', 'Observacion', 'Respuesta'], caption: 'Loop agentic basico' },
  }),
  s({
    id: 42,
    chapter: 'Agentes',
    layout: 'framework',
    title: 'ReAct: razonar y actuar',
    claim: 'Los agentes modernos alternan pensamiento, accion y observacion.',
    proof: 'Este patron permite corregir rumbo con evidencia del entorno, no solo con texto interno.',
    source: 'masterGuide',
    accent: 'violet',
    items: ['Reason', 'Act', 'Observe', 'Reflect', 'Answer'],
  }),
  s({
    id: 43,
    chapter: 'Agentes',
    layout: 'big-statement',
    title: 'La autonomia sin limites es mala ingenieria.',
    claim: 'Un agente confiable necesita permisos, sandbox, trazabilidad y puntos humanos de aprobacion.',
    proof: 'Mientras mas accion ejecuta, mas importante es reducir superficie de dano.',
    source: 'masterGuide',
    accent: 'navy',
  }),
  s({
    id: 44,
    chapter: 'Agentes',
    layout: 'data-chart',
    title: 'Los agentes estan mejorando en tareas largas',
    claim: 'La pregunta tecnica ya no es solo si responde, sino cuanto trabajo puede completar con fiabilidad.',
    proof: 'METR mide horizontes de tiempo de tareas que agentes frontier completan con probabilidades de exito.',
    source: 'metr',
    accent: 'mint',
    metric: { value: '50%', label: 'time horizon como umbral de exito', helper: 'duracion donde el agente acierta la mitad de veces' },
    chart: { type: 'steps', data: [{ label: 'Minutos', value: 18 }, { label: 'Decenas min', value: 42 }, { label: 'Horas', value: 72 }, { label: 'Mas contexto', value: 88 }], caption: 'Lectura conceptual de madurez agentic' },
  }),
  s({
    id: 45,
    chapter: 'Agentes',
    layout: 'quote',
    title: 'El agente como nuevo integrante del equipo',
    claim: 'Dirigir agentes se parece menos a escribir prompts y mas a gestionar trabajo delegado.',
    proof: 'Microsoft posiciona al agent boss como rol emergente de coordinacion humano-agente.',
    source: 'microsoft',
    accent: 'blue',
    quote: { text: 'No se micromanagea: se disena confianza informada.', author: 'AECODE sobre WorkLab', role: 'Lectura ejecutiva' },
  }),
  s({
    id: 46,
    chapter: 'Agentes',
    layout: 'diagram',
    title: 'MCP: conectores como infraestructura',
    claim: 'El valor de un agente crece cuando puede conectarse a herramientas y datos sin integraciones fragiles.',
    proof: 'El Model Context Protocol estructura conexiones semanticas entre modelos y sistemas externos.',
    source: 'masterGuide',
    accent: 'green',
    diagram: { nodes: ['Modelo', 'MCP', 'Drive', 'GitHub', 'DB', 'Notion'], caption: 'Acoplamiento abierto para herramientas' },
  }),
  s({
    id: 47,
    chapter: 'Agentes',
    layout: 'matrix',
    title: 'Tipos de agentes utiles',
    claim: 'No todos los agentes deben ser autonomos; cada tipo necesita controles distintos.',
    proof: 'Un agente de investigacion, uno de codigo y uno operativo tienen riesgos y metricas diferentes.',
    source: 'masterGuide',
    accent: 'violet',
    columns: [
      { title: 'Research', items: ['Busca', 'Resume', 'Cita'] },
      { title: 'Builder', items: ['Edita codigo', 'Prueba', 'Propone PR'] },
      { title: 'Operativo', items: ['Ejecuta flujo', 'Actualiza sistemas', 'Escala excepciones'] },
    ],
  }),
  s({
    id: 48,
    chapter: 'Agentes',
    layout: 'image',
    title: 'Multiagente no significa caos',
    claim: 'Un sistema multiagente maduro divide responsabilidades, no multiplica ruido.',
    proof: 'La arquitectura debe definir roles, memoria compartida, handoffs y criterios de salida.',
    source: 'gartner',
    accent: 'mint',
    visual: 'agents',
  }),
  s({
    id: 49,
    chapter: 'Agentes',
    layout: 'data-chart',
    title: 'Codex muestra el futuro del trabajo tecnico',
    claim: 'El desarrollo de software ya se mueve hacia delegacion paralela a agentes.',
    proof: 'OpenAI reporta que Codex se volvio integral internamente y casi todos sus ingenieros lo usan.',
    source: 'openai',
    accent: 'blue',
    metric: { value: 'casi todos', label: 'ingenieros OpenAI usan Codex', helper: 'segun anuncio de GA' },
    chart: { type: 'bars', data: [{ label: 'Julio', value: 55 }, { label: 'Octubre', value: 92 }], caption: 'De uso mayoritario a uso casi universal' },
  }),
  s({
    id: 50,
    chapter: 'Agentes',
    layout: 'chapter',
    title: 'Capitulo 5: impacto profesional',
    claim: 'La IA no elimina profesiones de una vez: primero reconfigura tareas, luego roles y finalmente estructuras.',
    proof: 'El profesional valioso aprende a orquestar sistemas, no solo a producir output.',
    source: 'masterGuide',
    accent: 'violet',
  }),
  s({
    id: 51,
    chapter: 'Trabajo',
    layout: 'big-statement',
    title: 'La IA reemplaza tareas antes que cargos.',
    claim: 'El riesgo real esta en trabajo transaccional sin criterio, no en profesiones completas con responsabilidad.',
    proof: 'Lectura de la guia: primero caen tareas aisladas, luego flujos mal disenados.',
    source: 'masterGuide',
    accent: 'navy',
  }),
  s({
    id: 52,
    chapter: 'Trabajo',
    layout: 'matrix',
    title: 'Tareas expuestas vs tareas defendibles',
    claim: 'Lo repetible, textual y verificable se automatiza antes; lo ambiguo y responsable exige humanos fuertes.',
    proof: 'La frontera se mueve hacia criterio, contexto, negociacion, diseno y accountability.',
    source: 'masterGuide',
    accent: 'blue',
    columns: [
      { title: 'Expuestas', items: ['Transcripcion', 'Clasificacion', 'Plantillas'] },
      { title: 'Aumentadas', items: ['Analisis', 'Documentacion', 'QA'] },
      { title: 'Defendibles', items: ['Criterio', 'Responsabilidad', 'Direccion'] },
    ],
  }),
  s({
    id: 53,
    chapter: 'Trabajo',
    layout: 'data-chart',
    title: 'La adopcion profesional sera desigual',
    claim: 'Quienes tienen mas capital educativo y tecnico capturan antes la productividad.',
    proof: 'Anthropic observa adopcion desigual por geografia y patron de uso, senalando riesgo de brechas.',
    source: 'anthropic',
    accent: 'green',
    metric: { value: 'desigual', label: 'patron de adopcion IA' },
    chart: { type: 'bars', data: [{ label: 'Alto acceso', value: 88 }, { label: 'Medio', value: 54 }, { label: 'Bajo', value: 31 }], caption: 'Representacion conceptual de brecha de adopcion' },
  }),
  s({
    id: 54,
    chapter: 'Trabajo',
    layout: 'opinion',
    title: 'El profesional promedio debe cambiar de identidad',
    claim: 'De operador de herramienta a arquitecto de resultados.',
    proof: 'El mercado pagara menos por ejecutar pasos y mas por disenar sistemas que produzcan evidencia.',
    source: 'aecode',
    accent: 'violet',
    items: ['Diagnostica', 'Disena', 'Orquesta', 'Valida', 'Comunica'],
  }),
  s({
    id: 55,
    chapter: 'Trabajo',
    layout: 'framework',
    title: 'Las cinco habilidades del agent boss',
    claim: 'Dirigir agentes exige criterio tecnico y gestion de trabajo.',
    proof: 'La habilidad diferencial es descomponer metas, delegar subtareas, evaluar salidas y corregir rumbo.',
    source: 'microsoft',
    accent: 'mint',
    items: ['Descomponer', 'Delegar', 'Evaluar', 'Integrar', 'Responder'],
  }),
  s({
    id: 56,
    chapter: 'Trabajo',
    layout: 'quote',
    title: 'El nuevo liderazgo tecnico',
    claim: 'Un lider fuerte no pregunta "que herramienta compro"; pregunta "que sistema operativo de trabajo necesito".',
    proof: 'La compra de software sin redisenho de flujo produce adoption theater.',
    source: 'aecode',
    accent: 'blue',
    quote: { text: 'El lider de IA no compra magia: disena capacidad operativa.', author: 'AECODE', role: 'Criterio ejecutivo' },
  }),
  s({
    id: 57,
    chapter: 'Trabajo',
    layout: 'checklist',
    title: 'Roles que suben de valor',
    claim: 'Los roles que conectan negocio, datos, software y criterio ganan poder.',
    proof: 'La IA aumenta a quien puede definir el problema, evaluar el output y convertirlo en decision.',
    source: 'masterGuide',
    accent: 'green',
    items: ['Product engineers', 'AI architects', 'Data owners', 'Technical PMs', 'Domain experts'],
  }),
  s({
    id: 58,
    chapter: 'Trabajo',
    layout: 'image',
    title: 'El aprendizaje se vuelve infraestructura laboral',
    claim: 'Aprender IA no es tomar cursos: es construir capacidad demostrable.',
    proof: 'Las empresas no necesitan diplomas; necesitan evidencia de desempeno en flujos reales.',
    source: 'aecodeDeck',
    accent: 'mint',
    visual: 'passport',
  }),
  s({
    id: 59,
    chapter: 'Trabajo',
    layout: 'diagram',
    title: 'De skill individual a skill verificable',
    claim: 'El mercado necesita ver lo que sabes hacer, no solo lo que viste en un curso.',
    proof: 'AECODE propone ruta, capsulas, practica, evidencia, feedback y validacion.',
    source: 'aecodeDeck',
    accent: 'violet',
    diagram: { nodes: ['Ruta', 'Capsula', 'Practica', 'Evidencia', 'Validacion'], caption: 'Skill Operating System' },
  }),
  s({
    id: 60,
    chapter: 'Trabajo',
    layout: 'chapter',
    title: 'Capitulo 6: IA en AEC',
    claim: 'AEC no necesita hype: necesita productividad, trazabilidad, control y evidencia.',
    proof: 'El sector puede capturar IA donde hay documentos, modelos, obra, riesgo y decisiones repetibles.',
    source: 'aecode',
    accent: 'blue',
    visual: 'aec',
  }),
  s({
    id: 61,
    chapter: 'AEC',
    layout: 'big-statement',
    title: 'El sector AEC no esta atrasado por falta de cursos.',
    claim: 'Esta frenado por la brecha entre aprender y ejecutar con evidencia.',
    proof: 'Los decks AECODE plantean que el mercado contrata skills demostrables, no certificados sueltos.',
    source: 'aecodeDeck',
    accent: 'navy',
  }),
  s({
    id: 62,
    chapter: 'AEC',
    layout: 'matrix',
    title: 'Donde entra IA en AEC',
    claim: 'IA aporta donde hay informacion fragmentada y decisiones de alto costo.',
    proof: 'BIM, documentos, RFIs, presupuestos, seguridad y avance de obra tienen patrones repetibles y datos verificables.',
    source: 'aecode',
    accent: 'mint',
    columns: [
      { title: 'Diseno', items: ['BIM QA', 'Normativa', 'Simulacion'] },
      { title: 'Obra', items: ['Avance', 'Seguridad', 'Evidencia visual'] },
      { title: 'Gestion', items: ['Reportes', 'Contratos', 'Riesgos'] },
    ],
  }),
  s({
    id: 63,
    chapter: 'AEC',
    layout: 'diagram',
    title: 'Copiloto tecnico de obra',
    claim: 'El caso de uso fuerte no es "chat de obra"; es flujo de evidencia y decision.',
    proof: 'Un sistema util conecta fotos, cronograma, metrados, incidencias y reportes.',
    source: 'aecode',
    accent: 'blue',
    diagram: { nodes: ['Foto', 'Modelo', 'Cronograma', 'Reporte', 'Decision'], caption: 'Vision + documentos + criterio tecnico' },
  }),
  s({
    id: 64,
    chapter: 'AEC',
    layout: 'data-chart',
    title: 'El aprendizaje AEC debe medirse como progreso',
    claim: 'La metrica no es asistencia: es skill completada con evidencia.',
    proof: 'AECODE define el aprendizaje como desempeno verificable, no consumo de contenido.',
    source: 'aecodeDeck',
    accent: 'green',
    metric: { value: 'Skill', label: 'unidad minima de valor profesional' },
    chart: { type: 'steps', data: defaultCharts.aecodeLoop, caption: 'Loop de skill verificable' },
  }),
  s({
    id: 65,
    chapter: 'AEC',
    layout: 'framework',
    title: 'Skill Graph AECODE',
    claim: 'Una ruta moderna debe conectar rol, skill, practica y evidencia.',
    proof: 'Asi el aprendizaje deja de ser biblioteca y se vuelve sistema de progresion profesional.',
    source: 'aecodeDeck',
    accent: 'violet',
    items: ['Rol objetivo', 'Skill gap', 'Capsulas', 'Practica aplicada', 'Evidencia'],
  }),
  s({
    id: 66,
    chapter: 'AEC',
    layout: 'opinion',
    title: 'BIM + IA no es un combo de buzzwords',
    claim: 'BIM aporta estructura; IA aporta interpretacion, automatizacion y asistencia cognitiva.',
    proof: 'Sin datos BIM ordenados, la IA improvisa; sin IA, BIM puede quedarse como repositorio subutilizado.',
    source: 'aecode',
    accent: 'mint',
    items: ['Modelo como fuente', 'IA como interprete', 'Evidencia como control'],
  }),
  s({
    id: 67,
    chapter: 'AEC',
    layout: 'image',
    title: 'El nuevo profesional AEC',
    claim: 'No sera el que memoriza software; sera el que arma sistemas de trabajo sobre software.',
    proof: 'La ventaja esta en automatizar, documentar, validar y comunicar decisiones tecnicas.',
    source: 'aecode',
    accent: 'blue',
    visual: 'aec',
  }),
  s({
    id: 68,
    chapter: 'AEC',
    layout: 'checklist',
    title: 'Casos de uso que si valen la pena',
    claim: 'Prioriza casos donde la IA reduzca friccion real del proyecto.',
    proof: 'Un caso bueno tiene datos disponibles, output verificable y dueno operativo.',
    source: 'aecode',
    accent: 'green',
    items: ['Reportes semanales', 'Revision documental', 'QA BIM', 'Minutas y acuerdos', 'Analisis de avance'],
  }),
  s({
    id: 69,
    chapter: 'AEC',
    layout: 'quote',
    title: 'La evidencia gana',
    claim: 'El futuro de la educacion tecnica no es mas contenido: es mas prueba de capacidad.',
    proof: 'Esto conecta aprendizaje, empleabilidad, certificacion y valor empresarial.',
    source: 'aecodeDeck',
    accent: 'violet',
    quote: { text: 'El mercado no contrata cursos. Contrata skills demostrables.', author: 'AECODE', role: 'Tesis de producto' },
  }),
  s({
    id: 70,
    chapter: 'AEC',
    layout: 'chapter',
    title: 'Capitulo 7: riesgos',
    claim: 'La IA mal gobernada puede acelerar errores, deuda tecnica y fuga de informacion.',
    proof: 'La madurez exige seguridad, privacidad, evaluacion, responsabilidad y criterios de no uso.',
    source: 'masterGuide',
    accent: 'navy',
    visual: 'risk',
  }),
  s({
    id: 71,
    chapter: 'Riesgos',
    layout: 'big-statement',
    title: 'La IA multiplica capacidad. Tambien multiplica mala arquitectura.',
    claim: 'Si el proceso esta roto, automatizarlo solo lo rompe mas rapido.',
    proof: 'La deuda tecnica por vibe coding descontrolado aparece cuando se apilan parches sin diseno.',
    source: 'masterGuide',
    accent: 'navy',
  }),
  s({
    id: 72,
    chapter: 'Riesgos',
    layout: 'matrix',
    title: 'Riesgos principales',
    claim: 'El riesgo no es una sola cosa: combina datos, seguridad, calidad y responsabilidad.',
    proof: 'Cada tipo de riesgo requiere control distinto; no se resuelve con una politica generica.',
    source: 'masterGuide',
    accent: 'violet',
    columns: [
      { title: 'Datos', items: ['PI', 'Privacidad', 'Permisos'] },
      { title: 'Calidad', items: ['Alucinacion', 'Sesgo', 'No reproducible'] },
      { title: 'Operacion', items: ['Accion indebida', 'Costos', 'Dependencia'] },
    ],
  }),
  s({
    id: 73,
    chapter: 'Riesgos',
    layout: 'opinion',
    title: 'El mayor riesgo: outputs sin dueno',
    claim: 'Si nadie responde por la decision, la IA se vuelve excusa organizacional.',
    proof: 'Todo sistema agentic debe tener responsable humano, logs y criterio de escalamiento.',
    source: 'aecode',
    accent: 'green',
    items: ['Owner', 'Registro', 'Aprobacion', 'Rollback'],
  }),
  s({
    id: 74,
    chapter: 'Riesgos',
    layout: 'diagram',
    title: 'Human-in-the-loop no es decoracion',
    claim: 'HITL debe ubicarse donde hay dano potencial, no al final como firma simbolica.',
    proof: 'Aprobaciones humanas reducen riesgo en acciones irreversibles, sensibles o costosas.',
    source: 'masterGuide',
    accent: 'blue',
    diagram: { nodes: ['Agente', 'Evalua riesgo', 'HITL', 'Accion', 'Auditoria'], caption: 'Control humano en puntos criticos' },
  }),
  s({
    id: 75,
    chapter: 'Riesgos',
    layout: 'checklist',
    title: 'Checklist de despliegue seguro',
    claim: 'Antes de produccion, prueba el sistema como si fuera a fallar.',
    proof: 'Sandbox, tests, permisos minimos y monitoreo reducen dano antes de escalar.',
    source: 'masterGuide',
    accent: 'mint',
    items: ['Sandbox', 'Eval set', 'Permisos minimos', 'Logs', 'Alertas', 'Rollback'],
  }),
  s({
    id: 76,
    chapter: 'Riesgos',
    layout: 'data-chart',
    title: 'No todo agente merece autonomia',
    claim: 'A mayor autonomia, mayor exigencia de evaluacion y control.',
    proof: 'El costo de error crece cuando el agente actua sobre sistemas reales.',
    source: 'masterGuide',
    accent: 'violet',
    metric: { value: '4 niveles', label: 'de autonomia operativa' },
    chart: { type: 'steps', data: [{ label: 'Sugiere', value: 22 }, { label: 'Prepara', value: 45 }, { label: 'Ejecuta con aprobacion', value: 70 }, { label: 'Ejecuta solo', value: 96 }], caption: 'Riesgo relativo por autonomia' },
  }),
  s({
    id: 77,
    chapter: 'Riesgos',
    layout: 'quote',
    title: 'Regla de oro',
    claim: 'No delegues a una IA una decision que tu organizacion no sabe evaluar.',
    proof: 'La evaluacion debe existir antes de automatizar la decision.',
    source: 'aecode',
    accent: 'navy',
    quote: { text: 'Si no puedes auditarlo, no lo autonomices.', author: 'AECODE', role: 'Principio de gobierno' },
  }),
  s({
    id: 78,
    chapter: 'Riesgos',
    layout: 'framework',
    title: 'Gobernanza minima',
    claim: 'La gobernanza debe ser ligera, pero real.',
    proof: 'Una organizacion necesita politicas de datos, uso permitido, revision y respuesta ante incidentes.',
    source: 'masterGuide',
    accent: 'green',
    items: ['Politica de datos', 'Casos permitidos', 'Evaluacion', 'Seguridad', 'Incidentes'],
  }),
  s({
    id: 79,
    chapter: 'Riesgos',
    layout: 'image',
    title: 'La confianza se disena',
    claim: 'Confiar en IA no es creerle: es construir mecanismos para detectar cuando falla.',
    proof: 'La confianza informada combina pruebas, fuentes, logs y supervision.',
    source: 'masterGuide',
    accent: 'mint',
    visual: 'risk',
  }),
  s({
    id: 80,
    chapter: 'Riesgos',
    layout: 'chapter',
    title: 'Capitulo 8: playbook practico',
    claim: 'La teoria vale si se traduce en habitos, repositorios y entregables.',
    proof: 'La adopcion real necesita rutinas de prompting, reglas, tests, contexto y mejora continua.',
    source: 'masterGuide',
    accent: 'blue',
  }),
  s({
    id: 81,
    chapter: 'Playbook',
    layout: 'framework',
    title: 'Marco CREATE',
    claim: 'Un buen prompt no es inspiracion: es especificacion operativa.',
    proof: 'Context, Request, Style, Attributes, Target y Examples ordenan la salida del modelo.',
    source: 'masterGuide',
    accent: 'violet',
    items: ['Context', 'Request', 'Style', 'Attributes', 'Target', 'Examples'],
  }),
  s({
    id: 82,
    chapter: 'Playbook',
    layout: 'diagram',
    title: 'Del prompt al repositorio de reglas',
    claim: 'Los equipos maduros no repiten instrucciones; las versionan.',
    proof: 'Archivos como CLAUDE.md, .cursorrules o playbooks reducen variabilidad y aceleran onboarding.',
    source: 'masterGuide',
    accent: 'mint',
    diagram: { nodes: ['Reglas', 'Repo', 'Agente', 'Diff', 'Test'], caption: 'Prompts convertidos en infraestructura' },
  }),
  s({
    id: 83,
    chapter: 'Playbook',
    layout: 'checklist',
    title: 'Rutina diaria de IA para builders',
    claim: 'La productividad aparece cuando la IA entra al ciclo normal de trabajo.',
    proof: 'Planear, ejecutar, revisar, documentar y aprender con IA evita usos aislados.',
    source: 'masterGuide',
    accent: 'green',
    items: ['Brief claro', 'Contexto cargado', 'Ejecucion controlada', 'Revision de diff', 'Leccion guardada'],
  }),
  s({
    id: 84,
    chapter: 'Playbook',
    layout: 'matrix',
    title: 'Que pedirle a la IA segun madurez',
    claim: 'No todas las tareas deben empezar con generacion completa.',
    proof: 'Un equipo nuevo debe empezar con analisis y revision antes de delegar ejecucion riesgosa.',
    source: 'aecode',
    accent: 'blue',
    columns: [
      { title: 'Inicial', items: ['Resumen', 'Ideas', 'Explicacion'] },
      { title: 'Intermedio', items: ['Borradores', 'QA', 'Automatizaciones'] },
      { title: 'Avanzado', items: ['Agentes', 'MCP', 'Workflows'] },
    ],
  }),
  s({
    id: 85,
    chapter: 'Playbook',
    layout: 'data-chart',
    title: 'Mide antes de enamorarte del demo',
    claim: 'Cada caso de IA debe tener una metrica antes de tocar codigo.',
    proof: 'Tiempo ahorrado, error reducido, velocidad de respuesta o calidad validada hacen defendible la inversion.',
    source: 'aecode',
    accent: 'violet',
    metric: { value: '1 metrica', label: 'por caso de uso antes del demo' },
    chart: { type: 'bars', data: [{ label: 'Tiempo', value: 82 }, { label: 'Calidad', value: 68 }, { label: 'Costo', value: 55 }, { label: 'Riesgo', value: 74 }], caption: 'Categorias de impacto medible' },
  }),
  s({
    id: 86,
    chapter: 'Playbook',
    layout: 'opinion',
    title: 'El mejor prompt es un proceso',
    claim: 'Si una tarea se repite, deja de escribir prompts sueltos y conviertela en workflow.',
    proof: 'Un workflow permite inputs estables, salidas comparables y mejora acumulada.',
    source: 'aecode',
    accent: 'green',
    items: ['Input normalizado', 'Pasos claros', 'Output validable', 'Memoria de mejoras'],
  }),
  s({
    id: 87,
    chapter: 'Playbook',
    layout: 'image',
    title: 'Segundo cerebro + agentes',
    claim: 'Tu sistema de conocimiento se vuelve mas valioso cuando una IA puede leerlo con estructura.',
    proof: 'Obsidian, Notion o repos Markdown funcionan mejor cuando hay taxonomia, indices y reglas de uso.',
    source: 'masterGuide',
    accent: 'mint',
    visual: 'brain',
  }),
  s({
    id: 88,
    chapter: 'Playbook',
    layout: 'quote',
    title: 'La velocidad sin revision es deuda',
    claim: 'Vibe coding funciona cuando se combina con ingenieria, tests y control de cambios.',
    proof: 'El problema no es construir rapido; es no saber que se cambio ni si sigue funcionando.',
    source: 'masterGuide',
    accent: 'navy',
    quote: { text: 'Construir rapido no exonera de pensar bien.', author: 'AECODE', role: 'Criterio de builder' },
  }),
  s({
    id: 89,
    chapter: 'Playbook',
    layout: 'timeline',
    title: 'Ruta practica de 24 semanas',
    claim: 'El aprendizaje serio va de control semantico a orquestacion multiagente.',
    proof: 'La guia propone fases: fundamentos, prototipado, automatizacion y multiagentes.',
    source: 'masterGuide',
    accent: 'blue',
    timeline: [
      { year: '1-4', label: 'Fundamentos', detail: 'Prompts, reglas y control.' },
      { year: '5-12', label: 'Web apps', detail: 'React, backend y despliegue.' },
      { year: '13-18', label: 'Automatizacion', detail: 'n8n, MCP y conectores.' },
      { year: '19-24', label: 'Multiagentes', detail: 'Estado, memoria y HITL.' },
    ],
  }),
  s({
    id: 90,
    chapter: 'Playbook',
    layout: 'chapter',
    title: 'Capitulo 9: postura AECODE',
    claim: 'La respuesta no es aprender mas herramientas: es construir capacidad verificable para la era agentic.',
    proof: 'AECODE debe convertir conocimiento en practica, evidencia y progreso profesional.',
    source: 'aecode',
    accent: 'violet',
    visual: 'passport',
  }),
  s({
    id: 91,
    chapter: 'AECODE',
    layout: 'big-statement',
    title: 'AECODE no debe ser una academia online.',
    claim: 'Debe ser un sistema operativo de habilidades verificables para AEC.',
    proof: 'El diferencial es diagnostico, ruta, practica, evidencia, feedback y validacion.',
    source: 'aecodeDeck',
    accent: 'navy',
  }),
  s({
    id: 92,
    chapter: 'AECODE',
    layout: 'diagram',
    title: 'El loop central',
    claim: 'El usuario debe sentir progreso profesional desde la primera skill.',
    proof: 'Entrar, diagnosticar, practicar, subir evidencia y recibir validacion es mas potente que navegar cursos.',
    source: 'aecode',
    accent: 'mint',
    diagram: { nodes: ['Entra', 'Diagnostico', 'Ruta', 'Practica', 'Evidencia', 'Validacion'], caption: 'Loop de aprendizaje AECODE' },
  }),
  s({
    id: 93,
    chapter: 'AECODE',
    layout: 'data-chart',
    title: 'North Star Metric',
    claim: 'La metrica que importa es skills verificadas con evidencia por usuario activo mensual.',
    proof: 'Esa metrica une aprendizaje, empleabilidad, retencion y valor B2B.',
    source: 'aecode',
    accent: 'green',
    metric: { value: 'Skills', label: 'verificadas con evidencia / MAU' },
    chart: { type: 'steps', data: defaultCharts.aecodeLoop, caption: 'De consumo a validacion' },
  }),
  s({
    id: 94,
    chapter: 'AECODE',
    layout: 'matrix',
    title: 'El stack de producto',
    claim: 'AECODE debe combinar contenido, IA, comunidad y validacion.',
    proof: 'La plataforma gana cuando cada pieza refuerza el progreso profesional medible.',
    source: 'aecode',
    accent: 'blue',
    columns: [
      { title: 'Learning', items: ['Capsulas', 'Practica', 'Rutas'] },
      { title: 'AI', items: ['Tutor', 'Feedback', 'Skill graph'] },
      { title: 'Proof', items: ['Evidencia', 'Rubrica', 'Passport'] },
    ],
  }),
  s({
    id: 95,
    chapter: 'AECODE',
    layout: 'opinion',
    title: 'La educacion tecnica debe volverse performativa',
    claim: 'No basta saber explicar: hay que poder demostrar con un artefacto.',
    proof: 'Un archivo, reporte, modelo, automatizacion o dashboard vale mas que una asistencia.',
    source: 'aecode',
    accent: 'violet',
    items: ['Artefacto', 'Criterio', 'Rubrica', 'Feedback', 'Iteracion'],
  }),
  s({
    id: 96,
    chapter: 'AECODE',
    layout: 'quote',
    title: 'La promesa',
    claim: 'AECODE debe ayudar a pasar de mirar la IA a construir con IA.',
    proof: 'El valor comercial aparece cuando el aprendizaje se convierte en portafolio verificable.',
    source: 'aecode',
    accent: 'mint',
    quote: { text: 'De hablar de IA a implementarla con evidencia.', author: 'AECODE', role: 'Promesa sintetica' },
  }),
  s({
    id: 97,
    chapter: 'AECODE',
    layout: 'checklist',
    title: 'Que debe hacer un lider despues de esta charla',
    claim: 'Salir inspirado no basta; hay que elegir un flujo y convertirlo en sistema.',
    proof: 'La accion concreta reduce el espacio entre vision y adopcion real.',
    source: 'aecode',
    accent: 'green',
    items: ['Elegir un flujo', 'Medir baseline', 'Prototipar con IA', 'Validar con usuarios', 'Escalar con gobierno'],
  }),
  s({
    id: 98,
    chapter: 'AECODE',
    layout: 'image',
    title: 'El futuro es un skill passport vivo',
    claim: 'La credencial fuerte no sera estatica: mostrara habilidades, evidencias y progreso.',
    proof: 'Un passport vivo conecta aprendizaje, empleabilidad, comunidad y certificacion.',
    source: 'aecodeDeck',
    accent: 'blue',
    visual: 'passport',
  }),
  s({
    id: 99,
    chapter: 'AECODE',
    layout: 'big-statement',
    title: 'La IA no premia al que sabe mas teoria.',
    claim: 'Premia al que convierte teoria en sistemas utiles antes que los demas.',
    proof: 'La nueva brecha profesional sera velocidad con criterio.',
    source: 'aecode',
    accent: 'violet',
  }),
  s({
    id: 100,
    chapter: 'Cierre',
    layout: 'cover',
    title: 'La era agentic ya empezo. La pregunta es que vas a construir con ella.',
    kicker: 'AECODE',
    claim: 'Aprender IA es aprender a dirigir sistemas de inteligencia hacia resultados verificables.',
    proof: 'La oportunidad AECODE es formar profesionales que no solo consumen IA: la implementan con criterio.',
    source: 'aecode',
    accent: 'green',
    visual: 'orb',
    metric: { value: 'Next', label: 'elige una skill, construye evidencia, valida progreso' },
  }),
];

if (slides.length !== 100) {
  throw new Error(`Expected exactly 100 slides, received ${slides.length}`);
}
